### ISSUE TITLE
[Gnome Shell] Dash to Dock default displays when using a custom indicator

### ISSUE THREAD

**Issue by oct2pus** [nana-4/materia-theme#295]
I would recommend removing the double dot and letting the user decide what looks best on their dock. Alternatively if you can get this to only work with the default theme, I'm certain some people would absolutely enjoy it! but i find it very hard to keep track of tiny dots and my current set up is part aesthetic part visibility for me.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version - Debian Packaged '20180928-1'
- GTK+ 3 version - 3.24.1
- Distribution (and version) - Debian Sid
- Desktop environment (and version) - Gnome 3.30.1
- Related application (and version) - Dash-to-Dock version 64
- Steps to reproduce
1) Enable Dash to Dock in Gnome-Tweaks
2) Go into the appearance tab and disable "Use Built-in Theme"
3) Swap to any indicator in "Customize window Counter Indicator" besides 'default'.
- Screenshot(s)

![image](https://user-images.githubusercontent.com/30452393/46920281-7ee68e00-cfb1-11e8-997f-d5d7bbf72850.png)

**Comment by PJSingh5000** [comment]
oct2pus,

Just to be clear, you are asking Materia theme to remove *all* running dots, so they can *only* be drawn by the Dash-to-Dock or the Dash-to-Panel extensions?

In your screen shots, there two different versions of running dots being displayed simultaneously:
1. One set is drawn by Dash-to-Dock, using the Metro style.
2. Another set drawn by Gnome-shell using the Materia theme (these are white).

(By the way, this also happens in the Ubuntu dock extension with the default theme as well; the dots from the extension and the ones from the theme overly on top of each other, so it is not noticeable. However, if you open lots of applications the two sets of running dots become misaligned and you can actually see them).

What happens if you disable your Dash-to-Dock extension? I presume the white dots drawn by the theme are be the only ones remaining?

If the theme supplies transparent running dot assets, or simply removes them, users not using the Dash-to-Dock extension would see no running dots at all.

The solution would need to support users who do not use a "dock" extension.

Therefore, the theme would need to detect if an extension is drawing its own dots. If there is no extension, the theme would have to provide the running dots.

Finally, I wonder if this is a bug in the Dash-to-Dock or the Dash-to-Panel extensions? May be something can be done on that side? Or perhaps Gnome-shell should be intelligent enough to know if an extension is supplying its own running dots, and stop displaying the ones from the current theme.

**Comment by oct2pus** [comment]
Actually I found the reality more annoying, I assumed "well it was an oversight and they probably just wanted to theme the default dock a bit more."

**
![image](https://user-images.githubusercontent.com/30452393/46945664-fd3b4280-d03a-11e8-9074-6cf91ad335ae.png)
**

The only extension turned on in this is User Themes, unless I'm very unaware of where these dots exist otherwise, it seems like this was intended to be a default theme for Dash-to-Dock gone awry.

**
![image](https://user-images.githubusercontent.com/30452393/46945696-1e039800-d03b-11e8-996e-27c3179dd5d9.png)
** 

for the sake of it i also turned off all user extensions besides dash-to-dock and User Themes. I also checked the codebase, there are a notable number of objects specifically referencing Dash-To-Dock under the [Gnome Shell Theme](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/3.30/gnome-shell-dark-compact.css)

```CSS
#dashtodockContainer #dash {
  background-color: rgba(0, 0, 0, 0.6);
}

#dashtodockContainer:overview #dash {
  background-color: rgba(255, 255, 255, 0.1);
}

#dashtodockContainer.extended:overview #dash {
  background-color: transparent;
}

#dashtodockContainer.left #dash,
#dashtodockContainer.right #dash {
  padding: 3px 0;
}

#dashtodockContainer.top #dash,
#dashtodockContainer.bottom #dash {
  padding: 0 3px;
}

#dashtodockContainer.extended #dash {
  padding: 0;
  border-radius: 0;
}

#dashtodockContainer.left .dash-item-container > StWidget,
#dashtodockContainer.right .dash-item-container > StWidget,
#dashtodockContainer.extended.left .dash-item-container > StWidget,
#dashtodockContainer.extended.right .dash-item-container > StWidget {
  padding: 3px 6px;
}

#dashtodockContainer.extended.left .dash-item-container:first-child > StWidget,
#dashtodockContainer.extended.right .dash-item-container:first-child > StWidget {
  padding: 6px 6px 3px 6px;
}

#dashtodockContainer.extended.left .dash-item-container:last-child > StWidget,
#dashtodockContainer.extended.right .dash-item-container:last-child > StWidget {
  padding: 3px 6px 6px 6px;
}

#dashtodockContainer.top .dash-item-container > StWidget,
#dashtodockContainer.bottom .dash-item-container > StWidget,
#dashtodockContainer.extended.top .dash-item-container > StWidget,
#dashtodockContainer.extended.bottom .dash-item-container > StWidget {
  padding: 6px 3px;
}

#dashtodockContainer.extended.top .dash-item-container:first-child > StWidget,
#dashtodockContainer.extended.bottom .dash-item-container:first-child > StWidget {
  padding: 6px 3px 6px 6px;
}

#dashtodockContainer.extended.top .dash-item-container:last-child > StWidget,
#dashtodockContainer.extended.bottom .dash-item-container:last-child > StWidget {
  padding: 6px 6px 6px 3px;
}

#dashtodockContainer .app-well-app-running-dot {
  background-color: transparent;
}

#dashtodockContainer .dash-item-container > StWidget {
  background-size: cover;
}

#dashtodockContainer.left .dash-item-container > StWidget.running1 {
  background-image: url("assets/dash/left-running1.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running1.focused {
  background-image: url("assets/dash/left-running1-focused.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running2 {
  background-image: url("assets/dash/left-running2.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running2.focused {
  background-image: url("assets/dash/left-running2-focused.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running3 {
  background-image: url("assets/dash/left-running3.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running3.focused {
  background-image: url("assets/dash/left-running3-focused.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running4 {
  background-image: url("assets/dash/left-running4.svg");
}

#dashtodockContainer.left .dash-item-container > StWidget.running4.focused {
  background-image: url("assets/dash/left-running4-focused.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running1 {
  background-image: url("assets/dash/right-running1.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running1.focused {
  background-image: url("assets/dash/right-running1-focused.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running2 {
  background-image: url("assets/dash/right-running2.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running2.focused {
  background-image: url("assets/dash/right-running2-focused.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running3 {
  background-image: url("assets/dash/right-running3.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running3.focused {
  background-image: url("assets/dash/right-running3-focused.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running4 {
  background-image: url("assets/dash/right-running4.svg");
}

#dashtodockContainer.right .dash-item-container > StWidget.running4.focused {
  background-image: url("assets/dash/right-running4-focused.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running1 {
  background-image: url("assets/dash/top-running1.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running1.focused {
  background-image: url("assets/dash/top-running1-focused.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running2 {
  background-image: url("assets/dash/top-running2.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running2.focused {
  background-image: url("assets/dash/top-running2-focused.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running3 {
  background-image: url("assets/dash/top-running3.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running3.focused {
  background-image: url("assets/dash/top-running3-focused.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running4 {
  background-image: url("assets/dash/top-running4.svg");
}

#dashtodockContainer.top .dash-item-container > StWidget.running4.focused {
  background-image: url("assets/dash/top-running4-focused.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running1 {
  background-image: url("assets/dash/bottom-running1.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running1.focused {
  background-image: url("assets/dash/bottom-running1-focused.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running2 {
  background-image: url("assets/dash/bottom-running2.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running2.focused {
  background-image: url("assets/dash/bottom-running2-focused.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running3 {
  background-image: url("assets/dash/bottom-running3.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running3.focused {
  background-image: url("assets/dash/bottom-running3-focused.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running4 {
  background-image: url("assets/dash/bottom-running4.svg");
}

#dashtodockContainer.bottom .dash-item-container > StWidget.running4.focused {
  background-image: url("assets/dash/bottom-running4-focused.svg");
}
```

so i want to say I don't believe this affects anybody else besides Dash-to-Dock users.
