### ISSUE TITLE
Legacy SSD title bar is not that compact, which is the right CSS selector?

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#357]
The SSD titlebars are quite big, even in compact variants of the theme.

I tried all sorts of selectors in order to reduce height, padding, etc. in my ~/.local theme which inherits from Materia-dark-compact to no avail.

Please notice that I'm not referring to CSD but to good old titlebars.

Any help will be much welcome!

**Comment by nana-4** [comment]
See: https://github.com/nana-4/materia-theme/issues/294#issuecomment-429509138 :)

**Comment by memeplex** [comment]
Thanks!

**Comment by memeplex** [comment]
Sorry for reopening this but I had no luck. Maybe I'm doing something wrong.

In ~/.local/share/themes/Neu/gtk-3.0/gtk.css I put:

```
@import url("/usr/share/themes/Materia-dark-compact/gtk-3.0/gtk.css");

.default-decoration {
	min-height: 0px;
	padding: 0px;
}
```

but nothing really happens. What else should I change?

**Comment by nana-4** [comment]
See the original CSS:

https://github.com/nana-4/materia-theme/blob/db26c9915c544121637b97f6a3d90eb07e11fec4/src/gtk/3.0/gtk-dark-compact.css#L1414-L1419

Since your CSS file is missing the additional `.titlebar:not(headerbar)` and `headerbar`, it doesn't override the style of the `@import` source CSS. So try as follows:

```css
@import url("/usr/share/themes/Materia-dark-compact/gtk-3.0/gtk.css");

.default-decoration.titlebar:not(headerbar),
headerbar.default-decoration {
  min-height: 0px;
  padding: 0px;
}
```

and don't forget to reload GNOME Shell. SSD title bar is somewhat special :)
