### ISSUE TITLE
How can I change the title buttons to pngs?

### ISSUE THREAD

**Issue by gsbhasin123** [nana-4/materia-theme#500]
I asked this to the plata developer, https://gitlab.com/tista500/plata-theme/-/issues/115, but since Plata is based on Materia and both have the same title button icons, I'd like to know the css I could put to change them to custom PNG images. Thanks in advance.

**Comment by nana-4** [comment]
Can you provide the PNGs that you want to replace?

**Comment by nana-4** [comment]
After the server down on the gitlab.com, I could check the link.

You say "I am trying to create an adapta clone", so I don't think this is the right place to ask it. Anyway I don't know much about plata or adapta, as I'm not the maintainer.

If you asked how to change the window control icons _in Materia_, I would have answered editing your icon theme...

Closing.

**Comment by gsbhasin123** [comment]
The same solution would apply to Materia so I also decided to ask here.

> If you asked how to change the window control icons in Materia, I would have suggested editing your icon theme...

Yeah but those are SVGs and I have PNG files from the Breeze theme.

**Comment by gsbhasin123** [comment]
I found some css and changed it to:
```css
.csd headerbar:not(.default-decoration) button.titlebutton.close:hover, .solid-csd headerbar:not(.default-decoration) button.titlebutton.close:hover { background-image: url("assets/window-close-ssd-eta-hover.png"); }
```
but that made hovering on the close button change it's color to white.
:thinking:
