### ISSUE TITLE
Selection color issue in firefox

### ISSUE THREAD

**Issue by ceyhunn** [nana-4/materia-theme#543]
- Materia version: latest
- GTK3 version: latest
- Distribution (and version): Manjaro Gnome Stable Branch
- Desktop environment (and version): Gnome latest
- Related application (and version): firefox latest

**Actual Issue**
Selection white text is unseen in dark background in firefox. 
![Screenshot from 2020-11-20 21-50-52](https://user-images.githubusercontent.com/5506156/99833038-ef8e0a80-2b7a-11eb-8735-2a61c70b57ae.png)

**Steps to Reproduce**
1. Visit any site with dark background.
2. Select any white text on it.

**Comment by rekaerst** [comment]
You can add this css to your ~/.config/gkt-3.0/gtk.css to change selection color
```css
.view selection,
.view:selected {
  background-color: replace-with-color-you-want; // e.g. rgb(223, 25, 157, 0.39)
}
```

https://user-images.githubusercontent.com/52642831/103457493-db712780-4d3a-11eb-8d98-bfe01be1ca50.mp4
