### ISSUE TITLE
nautilus window background 

### ISSUE THREAD

**Issue by Tuxino88** [nana-4/materia-theme#558]
Would it be possible to insert a background in the nautilus window?

![Schermata da 2021-03-24 16-22-53](https://user-images.githubusercontent.com/75674245/112336588-7dab0680-8cbd-11eb-8e79-2523c5a7e2ed.png)

**Comment by nana-4** [comment]
Sorry, but I'm not going to support it in this theme. That said, you could insert a background yourself. Paste such a CSS snippet into `~/.config/gtk-3.0/gtk.css`.

```css
.nautilus-window.background {
  background-image: url("path/to/your/image/file");
  background-size: 600px 400px;
  background-repeat: no-repeat;
  background-position: bottom right;
}
```

Note that the styles in `~/.config/gtk-3.0/gtk.css` affect every theme. If you want to apply it only to Materia, you need to edit this theme directly.
